apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sample-node-platform
  namespace: argocd
spec:
  description: Project for the sample node app and supporting ingress controller.
  sourceRepos:
    - https://github.com/meghasharma1102/sample-argocd-aks-github-deployment.git
    - https://kubernetes.github.io/ingress-nginx
  destinations:
    - namespace: demo-argocd
      server: https://kubernetes.default.svc
    - namespace: ingress-nginx
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
