apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-node-app.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  APP_NAME: {{ .Values.config.APP_NAME | quote }}
  APP_MESSAGE: {{ .Values.config.APP_MESSAGE | quote }}
  STORAGE_PATH: {{ .Values.config.STORAGE_PATH | quote }}
