apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-node-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "sample-node-app.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
